name: Automated Blog Generation

on:
  schedule:
    # Run twice a week (every Monday and Thursday at 9 AM UTC)
    - cron: '0 9 * * 1,4'
  workflow_dispatch:
    # Allow manual trigger from GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run scraper
        run: |
          python src/scraper.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Generate articles
        run: |
          python src/generator.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Build site
        run: |
          python src/builder.py
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: static # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
          commit-message: "Blog updated - ${{ github.event.head_commit.message }}"
          clean: true
      
      - name: Report status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Blog successfully generated and deployed!"
          else
            echo "Blog generation or deployment failed. Check logs for details."
          fi
